# Generated by Django 3.2.3 on 2021-05-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('preco_do_produto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('marca_do_produto', models.CharField(max_length=40)),
            ],
        ),
    ]
